package io.github.emiliasamaemt.bluemaprailway.exporter;

import com.flowpowered.math.vector.Vector3d;
import io.github.emiliasamaemt.bluemaprailway.model.RailLine;
import io.github.emiliasamaemt.bluemaprailway.model.RailScanResult;
import io.github.emiliasamaemt.bluemaprailway.model.RailType;
import io.github.emiliasamaemt.bluemaprailway.station.RailStation;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

public final class SvgRailExporter {

    private final JavaPlugin plugin;

    public SvgRailExporter(JavaPlugin plugin) {
        this.plugin = plugin;
    }

    public Path export(RailScanResult result, List<RailStation> stations) throws IOException {
        String directoryName = plugin.getConfig().getString("export.svg.directory", "export");
        String fileName = plugin.getConfig().getString("export.svg.file", "railways.svg");

        Path directory = plugin.getDataFolder().toPath().resolve(directoryName).normalize();
        Files.createDirectories(directory);

        Path outputFile = directory.resolve(fileName).normalize();
        Path parent = outputFile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        Files.writeString(outputFile, buildSvg(result, stations), StandardCharsets.UTF_8);
        return outputFile;
    }

    private String buildSvg(RailScanResult result, List<RailStation> stations) {
        Bounds bounds = boundsFor(result.lines(), stations);
        double padding = Math.max(0, plugin.getConfig().getDouble("export.svg.padding", 16.0));
        double viewBoxX = bounds.minX() - padding;
        double viewBoxY = bounds.minZ() - padding;
        double viewBoxWidth = Math.max(1.0, bounds.width() + padding * 2);
        double viewBoxHeight = Math.max(1.0, bounds.height() + padding * 2);

        StringBuilder svg = new StringBuilder();
        svg.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        svg.append("<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" viewBox=\"")
                .append(format(viewBoxX)).append(' ')
                .append(format(viewBoxY)).append(' ')
                .append(format(viewBoxWidth)).append(' ')
                .append(format(viewBoxHeight)).append("\">\n");
        svg.append("  <title>").append(escapeXml(plugin.getConfig().getString("export.svg.title", "BlueMap Railway"))).append("</title>\n");
        svg.append("  <desc>Generated by BlueMapRailway at ").append(Instant.now()).append("</desc>\n");
        svg.append("  <style>\n");
        svg.append("    .rail-line { fill: none; stroke-linecap: round; stroke-linejoin: round; }\n");
        svg.append("    .station { fill: white; stroke: black; stroke-width: 2; }\n");
        svg.append("    .station-label { font-family: sans-serif; font-size: 13px; paint-order: stroke; stroke: white; stroke-width: 3px; }\n");
        svg.append("  </style>\n");
        svg.append("  <g id=\"railways\" data-rail-count=\"").append(result.railCount())
                .append("\" data-line-count=\"").append(result.lineCount())
                .append("\" data-scanned-chunks=\"").append(result.scannedChunks()).append("\">\n");

        List<RailLine> lines = result.lines().stream()
                .sorted(Comparator.comparing(RailLine::worldName)
                        .thenComparing(this::routeKey)
                        .thenComparing(line -> line.type().name())
                        .thenComparing(line -> line.powered()))
                .toList();

        String currentWorld = null;
        String currentRoute = null;
        int index = 0;
        for (RailLine line : lines) {
            if (!line.worldName().equals(currentWorld)) {
                if (currentWorld != null) {
                    if (currentRoute != null) {
                        svg.append("      </g>\n");
                        currentRoute = null;
                    }
                    svg.append("    </g>\n");
                }

                currentWorld = line.worldName();
                svg.append("    <g id=\"world-").append(escapeId(currentWorld)).append("\" data-world=\"")
                        .append(escapeXml(currentWorld)).append("\">\n");
            }

            String routeKey = routeKey(line);
            if (!routeKey.equals(currentRoute)) {
                if (currentRoute != null) {
                    svg.append("      </g>\n");
                }

                currentRoute = routeKey;
                svg.append("      <g id=\"route-").append(escapeId(routeKey)).append("\" data-route-key=\"")
                        .append(escapeXml(routeKey)).append("\"");
                if (line.routeId() != null) {
                    svg.append(" data-route-id=\"").append(escapeXml(line.routeId())).append("\"")
                            .append(" data-route-name=\"").append(escapeXml(line.routeName())).append("\"");
                }
                svg.append(">\n");
            }

            appendLine(svg, line, index);
            index++;
        }

        if (currentWorld != null) {
            if (currentRoute != null) {
                svg.append("      </g>\n");
            }
            svg.append("    </g>\n");
        }

        appendStations(svg, stations);
        svg.append("  </g>\n");
        svg.append("</svg>\n");
        return svg.toString();
    }

    private void appendLine(StringBuilder svg, RailLine line, int index) {
        svg.append("        <polyline id=\"rail-line-").append(index)
                .append("\" class=\"rail-line\" data-world=\"").append(escapeXml(line.worldName()))
                .append("\" data-component-id=\"").append(escapeXml(line.componentId()))
                .append("\" data-type=\"").append(line.type().configKey())
                .append("\" data-powered=\"").append(line.powered());

        if (line.routeId() != null) {
            svg.append("\" data-route-id=\"").append(escapeXml(line.routeId()))
                    .append("\" data-route-name=\"").append(escapeXml(line.routeName()));
        }

        svg.append("\" stroke=\"").append(escapeXml(colorFor(line)))
                .append("\" stroke-width=\"").append(lineWidthFor(line)).append('"');

        if (plugin.getConfig().getBoolean("export.svg.non-scaling-stroke", true)) {
            svg.append(" vector-effect=\"non-scaling-stroke\"");
        }

        svg.append(" points=\"");
        for (int i = 0; i < line.points().size(); i++) {
            Vector3d point = line.points().get(i);
            if (i > 0) {
                svg.append(' ');
            }

            svg.append(format(point.getX())).append(',').append(format(point.getZ()));
        }

        svg.append("\">\n");
        svg.append("          <title>")
                .append(escapeXml(titleFor(line)))
                .append(" / ")
                .append(escapeXml(line.type().configKey()))
                .append("</title>\n");
        svg.append("        </polyline>\n");
    }

    private void appendStations(StringBuilder svg, List<RailStation> stations) {
        if (stations.isEmpty()) {
            return;
        }

        svg.append("    <g id=\"stations\">\n");
        for (RailStation station : stations) {
            Vector3d center = station.center();
            svg.append("      <g id=\"station-").append(escapeId(station.id()))
                    .append("\" data-station-id=\"").append(escapeXml(station.id()))
                    .append("\" data-world=\"").append(escapeXml(station.worldName())).append("\">\n");
            svg.append("        <circle class=\"station\" cx=\"").append(format(center.getX()))
                    .append("\" cy=\"").append(format(center.getZ())).append("\" r=\"6\" />\n");
            svg.append("        <text class=\"station-label\" x=\"").append(format(center.getX() + 9))
                    .append("\" y=\"").append(format(center.getZ() - 9)).append("\">")
                    .append(escapeXml(station.name())).append("</text>\n");
            svg.append("      </g>\n");
        }
        svg.append("    </g>\n");
    }

    private String routeKey(RailLine line) {
        if (line.routeId() == null || line.routeId().isBlank()) {
            return "unclassified";
        }

        return line.routeId();
    }

    private String titleFor(RailLine line) {
        if (line.routeName() != null && !line.routeName().isBlank()) {
            return line.worldName() + " / " + line.routeName() + " / " + line.componentId();
        }

        return line.worldName() + " / " + line.componentId();
    }

    private String colorFor(RailLine line) {
        if (line.routeColor() != null && !line.routeColor().isBlank()) {
            return line.routeColor();
        }

        return colorFor(line.type(), line.powered());
    }

    private int lineWidthFor(RailLine line) {
        if (line.routeLineWidth() > 0) {
            return line.routeLineWidth();
        }

        return plugin.getConfig().getInt("markers.line-width", 5);
    }

    private String colorFor(RailType type, boolean powered) {
        String key = "markers.colors." + type.configKey();
        if (type == RailType.POWERED_RAIL && !powered) {
            key = "markers.colors.powered-rail-inactive";
        }

        String fallback = type == RailType.POWERED_RAIL && !powered ? "#a16207" : "#9ca3af";
        return plugin.getConfig().getString(key, fallback);
    }

    private Bounds boundsFor(List<RailLine> lines, List<RailStation> stations) {
        double minX = Double.POSITIVE_INFINITY;
        double minZ = Double.POSITIVE_INFINITY;
        double maxX = Double.NEGATIVE_INFINITY;
        double maxZ = Double.NEGATIVE_INFINITY;

        for (RailLine line : lines) {
            for (Vector3d point : line.points()) {
                minX = Math.min(minX, point.getX());
                minZ = Math.min(minZ, point.getZ());
                maxX = Math.max(maxX, point.getX());
                maxZ = Math.max(maxZ, point.getZ());
            }
        }

        for (RailStation station : stations) {
            Vector3d center = station.center();
            minX = Math.min(minX, center.getX());
            minZ = Math.min(minZ, center.getZ());
            maxX = Math.max(maxX, center.getX());
            maxZ = Math.max(maxZ, center.getZ());
        }

        if (!Double.isFinite(minX)) {
            return new Bounds(0, 0, 100, 100);
        }

        return new Bounds(minX, minZ, maxX, maxZ);
    }

    private String format(double value) {
        return String.format(Locale.ROOT, "%.3f", value);
    }

    private String escapeXml(String value) {
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&apos;");
    }

    private String escapeId(String value) {
        return value.replaceAll("[^A-Za-z0-9_-]", "-");
    }

    private record Bounds(double minX, double minZ, double maxX, double maxZ) {
        double width() {
            return maxX - minX;
        }

        double height() {
            return maxZ - minZ;
        }
    }
}
