package io.github.emiliasamaemt.bluemaprailway.exporter;

import com.flowpowered.math.vector.Vector3d;
import io.github.emiliasamaemt.bluemaprailway.model.RailLine;
import io.github.emiliasamaemt.bluemaprailway.model.RailScanResult;
import io.github.emiliasamaemt.bluemaprailway.model.RailType;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

public final class SvgRailExporter {

    private final JavaPlugin plugin;

    public SvgRailExporter(JavaPlugin plugin) {
        this.plugin = plugin;
    }

    public Path export(RailScanResult result) throws IOException {
        String directoryName = plugin.getConfig().getString("export.svg.directory", "export");
        String fileName = plugin.getConfig().getString("export.svg.file", "railways.svg");

        Path directory = plugin.getDataFolder().toPath().resolve(directoryName).normalize();
        Files.createDirectories(directory);

        Path outputFile = directory.resolve(fileName).normalize();
        Path parent = outputFile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        Files.writeString(outputFile, buildSvg(result), StandardCharsets.UTF_8);
        return outputFile;
    }

    private String buildSvg(RailScanResult result) {
        Bounds bounds = boundsFor(result.lines());
        double padding = Math.max(0, plugin.getConfig().getDouble("export.svg.padding", 16.0));
        double viewBoxX = bounds.minX() - padding;
        double viewBoxY = bounds.minZ() - padding;
        double viewBoxWidth = Math.max(1.0, bounds.width() + padding * 2);
        double viewBoxHeight = Math.max(1.0, bounds.height() + padding * 2);

        StringBuilder svg = new StringBuilder();
        svg.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        svg.append("<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" viewBox=\"")
                .append(format(viewBoxX)).append(' ')
                .append(format(viewBoxY)).append(' ')
                .append(format(viewBoxWidth)).append(' ')
                .append(format(viewBoxHeight)).append("\">\n");
        svg.append("  <title>").append(escapeXml(plugin.getConfig().getString("export.svg.title", "BlueMap Railway"))).append("</title>\n");
        svg.append("  <desc>Generated by BlueMapRailway at ").append(Instant.now()).append("</desc>\n");
        svg.append("  <style>\n");
        svg.append("    .rail-line { fill: none; stroke-linecap: round; stroke-linejoin: round; }\n");
        svg.append("  </style>\n");
        svg.append("  <g id=\"railways\" data-rail-count=\"").append(result.railCount())
                .append("\" data-line-count=\"").append(result.lineCount())
                .append("\" data-scanned-chunks=\"").append(result.scannedChunks()).append("\">\n");

        List<RailLine> lines = result.lines().stream()
                .sorted(Comparator.comparing(RailLine::worldName)
                        .thenComparing(line -> line.type().name())
                        .thenComparing(line -> line.powered()))
                .toList();

        String currentWorld = null;
        int index = 0;
        for (RailLine line : lines) {
            if (!line.worldName().equals(currentWorld)) {
                if (currentWorld != null) {
                    svg.append("    </g>\n");
                }

                currentWorld = line.worldName();
                svg.append("    <g id=\"world-").append(escapeId(currentWorld)).append("\" data-world=\"")
                        .append(escapeXml(currentWorld)).append("\">\n");
            }

            appendLine(svg, line, index);
            index++;
        }

        if (currentWorld != null) {
            svg.append("    </g>\n");
        }

        svg.append("  </g>\n");
        svg.append("</svg>\n");
        return svg.toString();
    }

    private void appendLine(StringBuilder svg, RailLine line, int index) {
        svg.append("      <polyline id=\"rail-line-").append(index)
                .append("\" class=\"rail-line\" data-world=\"").append(escapeXml(line.worldName()))
                .append("\" data-type=\"").append(line.type().configKey())
                .append("\" data-powered=\"").append(line.powered())
                .append("\" stroke=\"").append(escapeXml(colorFor(line.type(), line.powered())))
                .append("\" stroke-width=\"").append(plugin.getConfig().getInt("markers.line-width", 5)).append('"');

        if (plugin.getConfig().getBoolean("export.svg.non-scaling-stroke", true)) {
            svg.append(" vector-effect=\"non-scaling-stroke\"");
        }

        svg.append(" points=\"");
        for (int i = 0; i < line.points().size(); i++) {
            Vector3d point = line.points().get(i);
            if (i > 0) {
                svg.append(' ');
            }

            svg.append(format(point.getX())).append(',').append(format(point.getZ()));
        }

        svg.append("\">\n");
        svg.append("        <title>")
                .append(escapeXml(line.worldName()))
                .append(" / ")
                .append(escapeXml(line.type().configKey()))
                .append("</title>\n");
        svg.append("      </polyline>\n");
    }

    private String colorFor(RailType type, boolean powered) {
        String key = "markers.colors." + type.configKey();
        if (type == RailType.POWERED_RAIL && !powered) {
            key = "markers.colors.powered-rail-inactive";
        }

        String fallback = type == RailType.POWERED_RAIL && !powered ? "#a16207" : "#9ca3af";
        return plugin.getConfig().getString(key, fallback);
    }

    private Bounds boundsFor(List<RailLine> lines) {
        double minX = Double.POSITIVE_INFINITY;
        double minZ = Double.POSITIVE_INFINITY;
        double maxX = Double.NEGATIVE_INFINITY;
        double maxZ = Double.NEGATIVE_INFINITY;

        for (RailLine line : lines) {
            for (Vector3d point : line.points()) {
                minX = Math.min(minX, point.getX());
                minZ = Math.min(minZ, point.getZ());
                maxX = Math.max(maxX, point.getX());
                maxZ = Math.max(maxZ, point.getZ());
            }
        }

        if (!Double.isFinite(minX)) {
            return new Bounds(0, 0, 100, 100);
        }

        return new Bounds(minX, minZ, maxX, maxZ);
    }

    private String format(double value) {
        return String.format(Locale.ROOT, "%.3f", value);
    }

    private String escapeXml(String value) {
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&apos;");
    }

    private String escapeId(String value) {
        return value.replaceAll("[^A-Za-z0-9_-]", "-");
    }

    private record Bounds(double minX, double minZ, double maxX, double maxZ) {
        double width() {
            return maxX - minX;
        }

        double height() {
            return maxZ - minZ;
        }
    }
}
